#########################
### Required settings ###
#########################

## Which IP should be used for the record: internal/external
IP="external"

## A/AAAA records to be updated. You can separate multiple records by comma. Use * for all records.
DNS_RECORDS="ddns1.example.com,ddns2.example.com"

## Cloudflare Zone ID. You can find this on the overview page of your domain
ZONE_ID="changeMe"

## Cloudflare Zone API Token
CLOUDFLARE_ZONE_API_TOKEN="changeMe"

## Use Cloudflare proxy
PROXIED="false"

## 120–7200 seconds or 1 for Auto
TTL=120

##############################
### Mode-specific settings ###
##############################

## Required for IP=external
## URLs used to determine your public IP. You can separate multiple URLs with commas.
EXTERNAL_IP_APIS="https://api.ipify.org/,https://icanhazip.com/,https://ifconfig.me/ip"

## Required for IP=internal
## Sets the local network interface to fetch the IP from
## e.g. eth0, wlan0, ...
INTERFACE="eth0"
